server:
  error:
    whitelabel:
      enabled: false


spring:
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  datasource:
    username: ${DB_USER:user}
    password: ${DB_PASSWORD:user}
    url: jdbc:${DB_DBMS:postgresql}://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:cities}
  liquibase:
    change-log: classpath:/db/liquibase/changelog.yml


