server:
  error:
    include-message: always # to show exception error reason
  port: 8080

management:
  endpoint.gateway.enabled: true
  endpoints.web.exposure.include: gateway

spring:
  application.name: gateway
  cloud:
    gateway:
      discovery.locator.enabled: true
      routes:
        - id: cities
          uri: lb://cities
          predicates:
            Path=/cities/**
          filters:
            - AuthFilter
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/auth/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://${DISCOVERY_HOST:localhost}:8761/eureka