server:
  port: 8080

management:
  endpoint.gateway.enabled: true
  endpoints.web.exposure.include: gateway

spring:
  application.name: gateway
  cloud:
    gateway:
      discovery.locator.enabled: true
      routes:
        - id: cities
          uri: lb://cities
          predicates:
            Path=/cities/**
          filters:
            - AuthFilter
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/auth/signIn,/auth/signIn

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka