spring:
  application:
    name: auth

server:
  port: 0
  servlet:
    context-path: /auth
  error:
    include-message: always # to show exception error reason

management:
  health:
    livenessState.enabled: true
    readinessState.enabled: true
  endpoint.health.probes.enabled: true

kndemo:
  auth:
    users:
      - login: pasha
        password: pasha

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

